### ISSUE TITLE
Upgrade WildFly to latest version?

### ISSUE THREAD

**Issue by psiroky** [kiegroup/kie-docker-ci-images#2]
We are currently using WildFly 8.1.0.Final images. There is already 8.2.1.Final and 9.0.1.Final available. Should we perhaps upgrade? Maybe only on master branch?

**Comment by mrietveld** [comment]
+1 for upgrading to 8.2.1.Final and 9.0.1.Final -- but _only_ on master. 

I'm already running into issues on 8.2.1.Final. 

-1 for upgrading to 10.x.

**Comment by psiroky** [comment]
For the CI Docker images, we really should just choose one version. I don't think we actually need images with multiple WildFly versions. It would mean creating and running several more containers with each build. (but it is definitely technically possible in case there would be a real need)

**Comment by romartin** [comment]
@psiroky I think this can be already closed..
